name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci
        
      - name: Test
        run: npm test

      - name: Build 
        run: npm expo start

      - name: Publish artifact
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: ./

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: app
          path: ./

      - name: Install dependencies
        run: npm ci --production

      # - name: Deployment script
        # run: |
          # Add your deployment commands here
          # For example, if deploying to a cloud service, you might have commands to deploy the app



